# Generated by Django 4.2.2 on 2023-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
